name: beautifulsoup
description: A dart port of the famous python library beautifulsoup
version: 0.0.1
homepage: https://github.com/Sach97/beautifulsoup.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
dependencies: 
  html: ^0.15.0
